Fix an issue where resolution of webDir would hang.
schultek/jaspr pull request #284
Opened 2024-08-27 14:29 UTC by dam5s

This solves issues when running the backend server during tests on a Windows machines where the existing solution would infinitely loop in search of the directory.

## Description

Previous implementation would look for the `pubspec.yaml` based on the location of the executable. When running tests on my Windows machine, that location is some random temporary directory. I added a fallback resolution based on the working directory (which is the project directory during tests).

I also made sure we would throw an exception if we could not actually resolve the directory, this informs the user and lets them set an environment variable instead.

The previous implementation would never resolve any directory on Windows machines during tests because the root dir would not satisfy the exit condition of the loop.

## Type of Change

🛠️ Bug fix 

## Ready Checklist

- [x] I've read the [Contribution Guide](https://github.com/schultek/jaspr/blob/main/CONTRIBUTING.md).
- [x] In case this PR changes one of the core packages, I've modified the respective **CHANGELOG.md** file using
      the [semantic_changelog](https://github.com/rrousselGit/semantic_changelog) format.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added myself to the AUTHORS file (optional, if you want to).

2024-09-03 10:54 UTC, schultek requested changes
Thanks for making this, looks good to me.

Adjust the changelog as shown, then I can approve.

2024-09-03 10:54 UTC, schultek commented on packages/jaspr/CHANGELOG.md
> +## 0.15.1
```suggestion
## Unreleased patch
```

2024-09-19 20:21 UTC, dam5s commented
> Thanks for making this, looks good to me.
> 
> Adjust the changelog as shown, then I can approve.

Done, thanks!

2024-09-19 20:33 UTC, dam5s commented
Just rebased, it should be a non-conflicting single commit now.

2024-09-28 19:27 UTC, schultek approved these changes
Thanks

2024-09-28 19:29 UTC, merged